In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data.csv', index_col=False)

In [3]:
df = data.copy()
df.head()

,Year,Sector,Subsector,Indicator,Country,Country_code,Amount,Rank
0,2010,Economy,Banking system access and depth,ATMs per 100000 adults,Afghanistan,AFG,0.53,165
1,2010,Economy,Banking system access and depth,ATMs per 100000 adults,Albania,ALB,34.13,83
2,2010,Economy,Banking system access and depth,ATMs per 100000 adults,Algeria,DZA,5.92,130
3,2010,Economy,Banking system access and depth,ATMs per 100000 adults,Angola,AGO,10.42,117
4,2010,Economy,Banking system access and depth,ATMs per 100000 adults,Antigua and Barbuda,ATG,72.07,32

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004538 entries, 0 to 1004537
Data columns (total 8 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Year          1004538 non-null  int64
 1   Sector        1004538 non-null  object
 2   Subsector     1004538 non-null  object
 3   Indicator     1004538 non-null  object
 4   Country       1004538 non-null  object
 5   Country_code  1004538 non-null  object
 6   Amount        1004538 non-null  float64
 7   Rank          1004538 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 61.3+ MB

In [5]:
df.describe()

               Year        Amount          Rank
count  1.004538e+06  1.004538e+06  1.004538e+06
mean   2.003980e+03  2.604685e+04  7.880816e+01
std    1.091980e+01  8.966807e+05  5.102201e+01
min    1.960000e+03 -9.899400e+02  1.000000e+00
25%    1.996000e+03  1.000000e+00  3.300000e+01
50%    2.005000e+03  1.423000e+01  7.500000e+01
75%    2.013000e+03  6.463000e+01  1.190000e+02
max    2.028000e+03  1.035670e+08  2.130000e+02